users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.home, name='home'),
    path("logout", views.logout_view),
    path("report/file", views.file_report, name='file_report'),
    path("report/<int:reportID>/submitted", views.report_submitted, name='report_submitted'),
    path("admin_reports", views.admin_reports, name='admin_reports'),
    path("user_reports", views.user_reports, name='user_reports'),
    path("user_reports/<int:report_id>/retract/", views.retract_report, name='retract_report'),
    path('report/<int:reportID>/comment', views.admin_reports, name='admin_comment'),

]

users/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from users.UserType import UserType
from storage_backends import MediaStorage


class User(models.Model):
    USER_TYPE_CHOICES = {
        (UserType.ANONYMOUS, "Anonymous"),
        (UserType.COMMON, "Common"),
        (UserType.IFC_ADMIN, "IFC JC Admin"),
        (UserType.IFC_COUNSELOR, "IFC JC Counselor"),
        (UserType.DJANGO_ADMIN, "Django Admin")
    }

    rolls = models.CharField(max_length=20, choices=USER_TYPE_CHOICES, default=UserType.COMMON)


class StandardOfConduct(models.Model):
    STANDARD_DESCRIPTIONS = {
        1: 'Physical abuse of any person on fraternity owned or controlled property or at fraternity sponsored or supervised functions, or conduct which threatens or endangers the health or safety of any person.',
        2: 'Damage to fraternity property, or property owned by a member of a fraternity, or to a visitor or guest of a fraternity.',
        3: 'Unauthorized entry into or occupation of fraternity facilities that are locked, closed to student activities, or otherwise restricted to use.',
        4: 'Unlawfully blocking or impeding normal pedestrian or vehicular traffic on or adjacent to fraternity property.',
        5: 'Disorderly conduct on fraternity owned, operated, or controlled property or at fraternity sponsored functions. This includes but is not limited to acts that breach the peace, or are deemed lewd, indecent or obscene, as well as excessive noise.',
        6: 'Conduct that is incompatible with the good character and personal responsibility expected of all members of the fraternity community and that dishonors the fraternity system at the University of Virginia.',
        7: 'Violations of University policies and procedures referenced in the FOA.',
        8: 'Failing to comply with the IFC Standards for Parties and Social Events.',
        9: 'Failing to comply with the IFC Rush Regulations.',
        10: 'Failing to comply with city/county ordinances governing residences, including garbage, shoveling snow from sidewalks, and noise levels.',
        11: 'Any violation of Federal, State, or Local law that directly affects the University’s pursuit of its proper educational purposes to the extent such violations are not covered by other Standards of Conduct.',
        12: 'Conduct that intentionally violates the rules of confidentiality or obstructs the operations of the IFCJC.',
        13: 'Hazing in violation of the Virginia statute or University regulations.',
        14: 'Failing to comply with directions of IFC officials acting under provisions 1-13 set out above.'
    }

    standard = models.IntegerField(unique=True, validators=[MinValueValidator(1), MaxValueValidator(14)])

    def clean(self):
        if not 1 <= self.standard <= 14:
            raise ValidationError('Standard must be an integer between 1 and 14.')

    def __str__(self):
        return f"{self.standard}. {self.STANDARD_DESCRIPTIONS.get(self.standard, 'Unknown Standard')}"


class Report(models.Model):
    def validate_date_of_incident(value):
        if value > timezone.now().date():
            raise ValidationError('Date of incident cannot be in the future.')

    STATUS_CHOICES = (
        ('new', 'New'),
        ('in progress', 'In Progress'),
        ('resolved', 'Resolved')
    )

    # fields without `blank=True` are required
    # db auto-populates fields changed from null=True to null=False with specified default values
    name_of_reporter = models.CharField(max_length=100, blank=True, default="")
    email_of_reporter = models.EmailField(blank=True, default="")
    phone_num_of_reporter = models.CharField(max_length=20, blank=True, default="")
    organization_of_reporter = models.CharField(max_length=100, blank=True, default="")
    date_of_incident = models.DateField(validators=[validate_date_of_incident])
    time_of_incident = models.TimeField()
    location_of_incident = models.CharField(max_length=150, default="")
    description_of_event = models.TextField()
    name_of_accused_fraternity = models.CharField(max_length=100, default="")
    violated_standards_conduct = models.ManyToManyField(StandardOfConduct)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new', null=True)
    admin_comment = models.TextField(blank=True, null=True)
    reviewer_comments = models.TextField(null=True, blank=True, default='No review yet')

    def __str__(self):
        return f"Report number {self.id} by {self.name_of_reporter} on {self.date_of_incident}"


class ReportFile(models.Model):
    report = models.ForeignKey(Report, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(blank=True, null=True, upload_to='uploads/', storage=MediaStorage())

    def __str__(self):
        return f"Uploaded file {self.file.name} for Report ID: {self.report.id}"

users/forms.py
from django import forms
from .models import Report, ReportFile, StandardOfConduct


class ReportForm(forms.ModelForm):
    violated_standards_conduct = forms.ModelMultipleChoiceField(
        queryset=StandardOfConduct.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label=''
    )

    phone_num_of_reporter = forms.CharField(
        widget=forms.TextInput(attrs={'type': 'tel', 'placeholder': 'Phone Number'}),
        required=False,
        label='Phone Number',
        help_text='Your phone number (optional)'
    )

    class Meta:
        model = Report
        fields = [
            'name_of_reporter',
            'email_of_reporter',
            'phone_num_of_reporter',
            'date_of_incident',
            'time_of_incident',
            'organization_of_reporter',
            'location_of_incident',
            'name_of_accused_fraternity',
            'description_of_event',
            'violated_standards_conduct'
        ]
        widgets = {
            'date_of_incident': forms.DateInput(attrs={'type': 'date'}),
            'time_of_incident': forms.TimeInput(attrs={'type': 'time'}),
        }
        labels = {
            'date_of_incident': 'Date of the incident',
            'organization_of_reporter': 'If you are part of a fraternity provide the name here',
            'location_of_incident': 'Location of the incident',
            'time_of_incident': 'Time of the incident',
            'name_of_accused_fraternity': 'Name of accused fraternity'
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ReportForm, self).__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields['name_of_reporter'].initial = user.get_full_name()
            self.fields['email_of_reporter'].initial = user.email
            self.fields['name_of_reporter'].widget = forms.HiddenInput()
            self.fields['email_of_reporter'].widget = forms.HiddenInput()
        else:
            del self.fields['name_of_reporter']
            del self.fields['email_of_reporter']
        required_fields = ['date_of_incident', 'time_of_incident', 'location_of_incident', 'name_of_accused_fraternity', 'description_of_event']
        for field_name in required_fields:
            field = self.fields.get(field_name)
            if field:
                field.required = True
                field.label = f"*{field.label}"


    def clean(self):
        cleaned_data = super().clean()
        standards = cleaned_data.get('violated_standards_conduct')
        return cleaned_data

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = ReportFile
        fields = [
            'file'
        ]

class AdminCommentForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['admin_comment']
        labels = {
            'admin_comment': 'Admin Comment'
        }

class ReportStatusForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['status']

users/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.urls import reverse, reverse_lazy
from django.contrib import messages


from .UserType import UserType
from django.http import HttpResponseForbidden
from .models import Report

# Create your views here.

from users.forms import ReportForm, UploadFileForm, AdminCommentForm
from users.models import Report, ReportFile


def is_site_admin(user):
    return user.groups.filter(name='Site Admin').exists()


def home(request):
    is_site_admin = request.user.groups.filter(name='SiteAdmin').exists()
    return render(request, "users/home.html", {'is_site_admin': is_site_admin})


def logout_view(request):
    logout(request)
    return redirect("/")


def file_report(request):
    max_size = 50 * 1024 * 1024  # 50 MB in bytes
    if request.method == 'POST':
        form = ReportForm(request.POST, user=request.user)
        files=request.FILES.getlist('document')
        if form.is_valid():

            if files: #check file type/size
                for file in files:
                    if not file.name.endswith(('.txt', '.pdf', '.jpg')):
                        return render(request, f'users/report/file.html', {'form': form, 'fileTypeError': True, 'fileSizeError': False})
                    if file.size > max_size:
                        return render(request, f'users/report/file.html', {'form': form, 'fileTypeError': False, 'fileSizeError': True})

            report = form.save(commit=False)
            if request.user.is_authenticated:
                report.name_of_reporter = request.user.get_full_name()
                report.email_of_reporter = request.user.email
            report.save()

            if files:
                for file in files:
                    originalFileName = file.name
                    newFileName = f'{report.id}{originalFileName}'  # The name format will be the report ID + the original name
                    file.name = newFileName
                    ReportFile.objects.create(report=report, file=file)
            form.save_m2m()
            return redirect(reverse('users:report_submitted', kwargs={'reportID': report.id}))
        else:
            print(form.errors)
    else:
        form = ReportForm(user=request.user)
    return render(request, 'users/report/file.html', {'form': form})


def report_submitted(request, reportID):
    if request.method == 'POST':
        form=UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            reportFile = form.save(commit=False)
            reportFile.report = Report.objects.filter(id=reportID).first()
            uploadedFile = request.FILES["document"]
            reportFile.file = uploadedFile

            originalFileName = uploadedFile.name
            newFileName = f'{reportID}{originalFileName}' #The name format will be the report ID + the original name
            reportFile.file.name = newFileName

            reportFile.save()
            return render(request, f'users/report/submitted.html', {'fileName': originalFileName}) #Show customer the original file name
            #return redirect(reverse('users:report_submitted', kwargs={'reportID': reportID}))
        else:
            print(form.errors)
    else:
        form = UploadFileForm()
    return render(request, f'users/report/submitted.html')


def handle_uploaded_file(f):
    with open("uploads/"+f.name, "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)


@login_required
@user_passes_test(is_site_admin, login_url=reverse_lazy('users:home'))
def admin_reports(request):
    reports_to_update = Report.objects.filter(status='new')
    for report in reports_to_update:
        report.status = 'in progress'
        report.save(update_fields=['status'])

    # Handling admin comments
    if 'admin_comment' in request.POST:
        comment_form = AdminCommentForm(request.POST)
        if comment_form.is_valid():
            report_id = request.POST.get('report_id')
            report = get_object_or_404(Report, id=report_id)
            report.admin_comment = comment_form.cleaned_data['admin_comment']
            report.save()
        else:
            pass

    # Handling status updates
    if 'new_status' in request.POST:
        report_id = request.POST.get('report_id')
        new_status = request.POST.get('new_status')
        report = get_object_or_404(Report, id=report_id)
        report.status = new_status
        report.save()

    # Get all reports
    reports = Report.objects.all().order_by('-created_at')
    forms = {report.id: AdminCommentForm(instance=report) for report in reports}
    return render(request, 'users/admin_reports.html', {'reports': reports, 'forms': forms})


@login_required
def user_reports(request):
    user_email = request.user.email
    reports = Report.objects.all().filter(email_of_reporter=user_email).order_by('-created_at')
    if request.method == 'POST':
        report_id = request.POST.get('report_id')
        report = get_object_or_404(Report, pk=report_id, email_of_reporter=user_email)
        if report.status == 'new':
            description = request.POST.get('description_of_event', '')
            if description:
                report.description_of_event = description
                report.save()
            else:
                return redirect('users:user_reports')
        else:
            return redirect('users:user_reports')
    return render(request, 'users/user_reports.html', {'reports': reports})



def retract_report(request, report_id):
    try:
        user_email = request.user.email
        report = Report.objects.get(pk=report_id, email_of_reporter=user_email)
        if report.status == 'new':
            report.delete()
            messages.success(request, "Your report has succesfully been retracted.")
        else:
            messages.error(request, 'You can only retract reports with the status "new".')
    except Report.DoesNotExist:
        messages.error(request, 'Report not found.')
    # return render(request, 'users/user_reports.html')
    return redirect('users:user_reports')

users/templates/users/footer.html
<footer class="footer">
    <div class="container">
        <p> DISCLAIMER: This is a school project that is not intended for actual use.</p>
    </div>
</footer>

users/templates/users/home.html
{% include "users/navbar.html" %}
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <style>
        body {
            text-align: center;
            padding-bottom: 30px;
        }

        .header-title {
            margin-top: 20px;
            font-size: 60px;
            font-weight: bold;
            flex: 1;
            margin-right: 1rem;
        }

        .header-section {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: -50px;
        }

        .report-details {

        }

        .scales-image {
            max-height: 120px;
            max-width: 100%;
        }

        .button-container {
            margin-top: 20px;
        }

        .button-container p {
            margin-top: 15px;
            font-size: 1.2em;
        }


        .content-container {
            text-align: left;
            padding: 1rem;
        }

        .subsection-title {
            font-size: 2rem;
            color: #555;
            margin-top: 3rem;
            margin-bottom: 3rem;
        }

        .how-it-works-list {
            list-style-type: none;
            padding-left: 0;
            margin-top: 0.5rem;
            margin-bottom: 4rem;
            margin-left: 1.5rem;
        }

        .how-it-works-list li {
            position: relative;
            margin-bottom: 1.5rem;
            padding-left: 40px;
        }

        .how-it-works-list li:before {
            content: '\27A4';
            color: #e87404;
            font-size: 20px;
            position: absolute;
            left: 0;
            top: 50%;
            transform: translateY(-50%);
        }

        .btn-custom {
            background-color: #e87404;
            font-family: 'Nanum Gothic', sans-serif;
            font-weight: bold;
            border-radius: 4px;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            position: relative;
            margin: 4px 2px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            -webkit-clip-path: polygon(15% 0%, 100% 0%, 85% 100%, 0% 100%);
            clip-path: polygon(15% 0%, 100% 0%, 85% 100%, 0% 100%);
        }

        .btn-custom:hover {
            background-color: #282c4c;
            color: white;
        }

        .btn-logout {
            background-color: #ff0000;
            font-family: 'Nanum Gothic', sans-serif;
            font-weight: bold;
            border-radius: 4px;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            position: relative;
            margin: 4px 2px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            -webkit-clip-path: polygon(15% 0%, 100% 0%, 85% 100%, 0% 100%);
            clip-path: polygon(15% 0%, 100% 0%, 85% 100%, 0% 100%);
        }

        .btn-logout:hover {
            background-color: #cc0000;
            color: white;
        }

        .button-container {
            display: flex;
            justify-content: space-around;
            width: 66.6%;
            margin: 2rem auto 4rem;
        }

        .btn-custom, .btn-logout {
            flex-grow: 1;
            text-align: center;
            margin: 0 10px;
            padding: 25px 35px;
        }


    </style>
</head>
<body>
<div class="container content-container">

    <div class="header-section d-flex justify-content-between align-items-center">
        <h1 class="header-title">Welcome to IFC Report It!</h1>
        <img src="{% static 'users/scales.png' %}" alt="Scales Image" class="img-fluid scales-image my-4">
    </div>
    <hr style="border: 1px solid #282c4c; width: 100%; margin: 35 auto;">
    <h2 class="subsection-title">How it works</h2>
    <ul class="how-it-works-list">
        <li>Gather the details for a case you'd like to report</li>
        <li>Log in below if you wish to attach your name to the case and receive email updates</li>
        <li>Complete the report form with as much information as possible</li>
        <li>Edit, retract, and view the status of any non-anonymous reports by clicking on "My Reports"</li>
    </ul>

    <h2 class="subsection-title">Log in or File a Report</h2>
    <div class="button-container mb-5">  <!-- Added large margin bottom for white space buffer -->
        {% if not user.is_authenticated %}
        <a href="{% provider_login_url 'google' %}" class="btn btn-custom">Login with Google</a>
        <a href="{% url 'users:file_report' %}" class="btn btn-custom">File an anonymous report</a>
        {% else %}
        <a href="logout" class="btn btn-logout">Log out</a>
        <a href="{% url 'users:file_report' %}" class="btn btn-custom">File a report as {{ user.get_full_name }}</a>
        {% endif %}
    </div>

    <!-- Information Section Below Button -->
    <h2 class="subsection-title">Scope</h2>
    <p class="report-details">
        This site is intended for people looking to directly report an incident to the Inter Fraternity Council Judicial
        Committee (IFC JC) for reasons including but not limited to hazing, rush violations, vandalism or physical harm,
        or high-risk social events in regards to fraternities at UVa. If you are looking to report incidents outside of
        the scope of the IFC, please refer to <a href="https://justreportit.virginia.edu/" target="_blank">justreportit.virginia.edu</a>.
    </p>

    <h2 class="subsection-title">How to contact</h2>
    <p class="report-details">
        If you have any problems using IFC Report it or would just like to speak to a representative in the IFC, visit room 171 in Newcomb Hall or reach out to Benjamin Ueltschey at zgd7wr@virginia.edu.
    </p>
</div>
    <footer class="footer">
        <div class="container">
            <p> DISCLAIMER: This is a school project that is not intended for actual use.</p>
        </div>
    </footer>

</body>

</html>

users/templates/users/navbar.html
{% load user_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
    <div class="container-fluid">
        <!-- Navbar header -->
        <span class="navbar-brand" style="pointer-events: none; cursor: default;" aria-disabled="true">IFC Report It</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarButtonsExample">
            <!-- Left links -->
            <ul class="navbar-nav mr-auto">
                {% url 'users:home' as home_url %}
                <li class="nav-item {% if request.path == home_url %} font-weight-bold {% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    {% url 'users:user_reports' as user_reports_url %}
                    <li class="nav-item {% if request.path == user_reports_url %} font-weight-bold {% endif %}">
                        <a class="nav-link" href="{{ user_reports_url }}">My Reports</a>
                    </li>
                {% endif %}
                {% if user|has_group:"Site Admin" %}
                    {% url 'users:admin_reports' as admin_reports_url %}
                    <li class="nav-item {% if request.path == admin_reports_url %} font-weight-bold {% endif %}">
                        <a class="nav-link" href="{{ admin_reports_url }}">Manage Reports</a>
                    </li>
                {% endif %}
            </ul>

        </div>
        <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
</nav>

users/templates/users/user_reports.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Previous Reports</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <style>
        .footer {
            bottom: 0;
            width: 100%;
            background-color: #f8f9fa;
            text-align: center;
            padding: 10px 0;
        }
        .button-container .btn {
            margin: 0 10px;
        }
        .btn-custom {
            background-color: #e87404; /* UVA Orange */
            color: white;
            font-family: 'Nanum Gothic', sans-serif;
            font-weight: bold;
        }
        .btn-custom:hover {
            background-color: #282c4c;
            color: white;
        }
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
            display: flex;
            flex-direction: column;
        }

        body > .content {
            flex-grow: 1;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }
        .content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            flex-grow: 1;
            padding: 1rem;
        }
        .footer {
            background-color: #f8f9fa;
            text-align: center;
            padding: 10px 0;
            width: 100%;
        }
    </style>
</head>
<body>
  {% include "users/navbar.html" %}
  {% load socialaccount %}
  {% block content %}
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
          {{ message }}
      </div>
    {% endfor %}
  </ul>
  {% endif %}
  <h2 class="mb-4 text-center">Your Reports</h2>
  <p class="text-center"><small><i>Reports may only be retracted if they are of new status, meaning they have not yet been viewed by an admin.</i></small></p>
  <div class="content">
    {% for report in reports %}
      <div class="card mb-3 w-75">
        <div class="card-header">
          <h5 class="mb-0">{{ report.name_of_reporter }}</h5>
        </div>
        <div class="card-body">
          <p class="mb-0"><strong>Created at:</strong> {{ report.created_at }}</p>
          <p><strong>Last updated:</strong> {{ report.updated_at }}</p>
          <p><strong>Status:</strong> {{ report.status|title }} </p>
        </div>

        <div class="card-footer">
          <button class="btn btn-custom details-button">Show Details</button>
          {% if report.status|lower == 'new' %}
          <a href="{% url 'users:retract_report' report.id %}" class="btn btn-danger btn-danger">
            <i class="fas fa-trash-alt"></i> Retract Report
          </a>
          {% endif %}

        </div>
        <div class="report-details" style="display: none;">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>Email:</strong> {{ report.email_of_reporter }}</li>
            <li class="list-group-item"><strong>Phone:</strong> {{ report.phone_num_of_reporter }}</li>
              <li class="list-group-item"><strong>Organization</strong> {{ report.organization_of_reporter }}</li>
              <li class="list-group-item"><strong>Date of Incident</strong> {{ report.date_of_incident }}</li>
              <li class="list-group-item"><strong>Time of Incident</strong> {{ report.time_of_incident }}</li>
              <li class="list-group-item"><strong>Location:</strong> {{ report.location_of_incident }}</li>
              <li class="list-group-item"><strong>Description:</strong> {{ report.description_of_event }}
                  {% if report.status == 'new' %}
                    <button class="btn btn-custom edit-description-button" data-report-id="{{ report.id }}">Edit Description</button>
                    <form method="post" class="edit-report-form" data-report-id="{{ report.id }}" style="display: none;">
                    {% csrf_token %}
                    <input type="hidden" name="report_id" value="{{ report.id }}">
                    <textarea name="description_of_event">{{ report.description_of_event }}</textarea>
                    <button class="btn btn-custom update-description-button">Update Report</button>
                    </form>
                  {% endif %}
              </li>
              <li class="list-group-item"><strong>Accused Fraternity:</strong> {{ report.name_of_accused_fraternity }}</li>
              <li class="list-group-item"><strong>Violated Standards of Conduct:</strong> {{ report.violated_standards_conduct.all|join:", " }}</li>
              {% if report.reviewer_comments %}
              <li class="list-group-item">
                  <strong>Reviewer Comments:</strong> {{ report.admin_comment }}
              </li>
          {% endif %}
            <li class="list-group-item">
            <strong>Uploaded Files:</strong>
            {% for file in report.files.all %}
                {% with reportID=report.id|stringformat:"s" %}
                {% with prefix="uploads/"|add:reportID %}
                {% with file_name=file.file.name|cut:prefix %}
               <ul><a href="https://ifc-jc-whistleblower-amazon-storage-bucket.s3.amazonaws.com/media/{{ file.file.name }}">{{ file_name }}</a></ul>
                {% endwith %}
                {% endwith %}
                {% endwith %}
            {% empty %}
              <ul><a>No file uploaded</a></ul>
            {% endfor %}
            </li>
            </ul>
        </div>
      </div>
    {% empty %}
      <p>No reports found.</p>
    {% endfor %}
      {% endblock %}
  </div>
<footer class="footer">
        <div class="container">
            <p> DISCLAIMER: This is a school project that is not intended for actual use.</p>
        </div>
    </footer>
<script>
  $(document).ready(function() {
    $('.details-button').click(function() {
      $(this).parent().next('.report-details').slideToggle();
      if ($(this).text() == 'Show Details') {
        $(this).text('Hide Details');
      } else {
        $(this).text('Show Details');
      }
    });
    $('.edit-description-button').click(function() {
      var reportId = $(this).data('report-id');
      $('.edit-report-form[data-report-id="' + reportId + '"]').slideToggle();
      $(this).toggle();
      $(this).siblings('div').toggle();
    });
  });
</script>
<script type="text/javascript">
  $(document).ready(function() {
      setTimeout(function() {
          $(".alert").fadeOut('slow');
      }, 3000);
  });
</script>
</body>
</html>